### ISSUE TITLE
error creating json web token

### ISSUE THREAD

**Issue by stanleyye** [ubclaunchpad/bounce#58]
The following occurs when i try to create a new user
```
[2018-08-11 21:52:43 +0000] [7] [ERROR] An error occurred during the handling of a POST request to LoginEndpoint                                                                                              
Traceback (most recent call last):                                                                     
  File "/usr/local/lib/python3.6/site-packages/jose/jws.py", line 163, in _sign_header_and_claims      
    key = jwk.construct(key_data, algorithm)                                                           
  File "/usr/local/lib/python3.6/site-packages/jose/jwk.py", line 61, in construct                     
    return key_class(key_data, algorithm)                                                              
  File "/usr/local/lib/python3.6/site-packages/jose/jwk.py", line 101, in __init__                     
    raise JWKError('Expecting a string- or bytes-formatted key.')                                      
jose.exceptions.JWKError: Expecting a string- or bytes-formatted key.                                  
                                                                                                       
During handling of the above exception, another exception occurred:                                    
                                                                                                       
Traceback (most recent call last):                                                                     
  File "/opt/bounce/bounce/server/api/__init__.py", line 117, in handle_request                        
    request, *args, **kwargs)                                                                          
  File "/opt/bounce/bounce/server/resource/__init__.py", line 109, in wrapper                          
    result = await coro(endpoint, request, *args, **kwargs)                                            
  File "/opt/bounce/bounce/server/api/auth.py", line 32, in post                                       
    token = util.create_jwt(user_row.identifier, self.server.config.secret)                            
  File "/opt/bounce/bounce/server/api/util.py", line 125, in create_jwt                                
    algorithm='HS256')                                                                                 
  File "/usr/local/lib/python3.6/site-packages/jose/jwt.py", line 61, in encode                        
    return jws.sign(claims, key, headers=headers, algorithm=algorithm)                                 
  File "/usr/local/lib/python3.6/site-packages/jose/jws.py", line 46, in sign                          
    signed_output = _sign_header_and_claims(encoded_header, encoded_payload, algorithm, key)           
  File "/usr/local/lib/python3.6/site-packages/jose/jws.py", line 166, in _sign_header_and_claims      
    raise JWSError(e)                                                                                  
jose.exceptions.JWSError: Expecting a string- or bytes-formatted key.                                  
[2018-08-11 21:52:43 +0000] - (sanic.access)[INFO][1:7]: POST http://localhost:8080/auth/login  500 33 
[2018-08-11 21:52:48 +0000] [7] [INFO] KeepAlive Timeout. Closing connection.                          
```

**Comment by stanleyye** [comment]
turns out i was missing `BOUNCE_SECRET` in my config
